import argparse
import os

from z3 import Solver

_PUZZLES_FOLDER = 'puzzles/'
_FLORIAN_FOLDER = 'florian/'


def puzzle_us_to_florian(puzzle: str) -> str:
    """Converts a puzzle from our format to Florian's format.

    @param puzzle: The puzzle in our format.
    @return: The puzzle in Florian's format.
    """
    face_1 = puzzle[0:4]
    face_2 = puzzle[4:8]
    face_3 = puzzle[8:12]
    face_4 = puzzle[12:16]
    face_5 = puzzle[16:20]
    face_6 = puzzle[20:24]

    face_1 = face_1[1] + face_1[3] + face_1[0] + face_1[2]
    face_2 = face_2[1] + face_2[3] + face_2[0] + face_2[2]
    face_3 = face_3[2] + face_3[0] + face_3[3] + face_3[1]
    face_4 = face_4[1] + face_4[3] + face_4[0] + face_4[2]
    face_5 = face_5[1] + face_5[3] + face_5[0] + face_5[2]
    face_6 = face_6[1] + face_6[3] + face_6[0] + face_6[2]

    return face_2 + face_1 + face_5 + face_3 + face_6 + face_4


def puzzle_file_to_florian(puzzle_file: str) -> None:
    """Converts a puzzle file to Florian's format.

    @param puzzle_file: The name of the puzzle file to be converted.
    """
    puzzle = open(f'{_PUZZLES_FOLDER}{puzzle_file}').readline()
    open(f'{_FLORIAN_FOLDER}{_PUZZLES_FOLDER}{puzzle_file}', 'w').write(puzzle_us_to_florian(puzzle))


def to_florians_dimacs(puzzle_file: str, number_of_moves: int) -> None:
    """Converts a puzzle file to Florian's format and runs rubiks_sat.py with the given number of moves.

    This function takes one of our puzzles files and transforms it into a file readable by Florian's rubiks_sat.py.
     Which in turn transforms it into a dimacs file.

    @param puzzle_file: The name of the puzzle file to be used.
    @param number_of_moves: The number of moves to be made in the solution.
    """
    puzzle_txt_file = puzzle_file + '.txt'
    puzzle_file_to_florian(puzzle_txt_file)

    os.system(
        f"""
python {_FLORIAN_FOLDER}/rubiks_sat.py {_FLORIAN_FOLDER}{_PUZZLES_FOLDER}{puzzle_txt_file} {number_of_moves} \
{puzzle_file}
        """
    )


def solve_florians_dimacs(puzzle_file: str) -> None:
    """Solves the rubiks cube problem using the dimacs file generated by Florian's rubiks_sat.py."""
    s = Solver()
    s.from_file(f'{_FLORIAN_FOLDER}dimacs/{puzzle_file}.dimacs')

    print(s.check())


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("path", type=str)
    parser.add_argument("nr_of_moves", type=int)
    args = parser.parse_args()

    to_florians_dimacs(args.path, args.nr_of_moves)
    solve_florians_dimacs(args.path)
