exclude = ['florian/*.py']
line-length = 120
[lint]
select = ["F", "E", "W", "C90", "I", "N", "D", "UP", "ARG", "PL", "PERF", "RUF"]
ignore = [
    "D100",
    "D205",
    "PLR0913",
    "PLR0911",
    "C901",
    "D401",
    "PLR2004",
    "PLR0912",
    "PLR0915",
    "RUF100",
]
[format]
docstring-code-line-length = 120
