name: test
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          pip install ruff
          ruff check --output-format=github .   
  test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v4
          with:
            python-version: '3.x'
        - run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - run: |
            pip install pytest
            pytest tests.py
